services:
  db:
    image: postgres
    restart: always
    ports:
      - '1212:5432'
    volumes:
      - /db/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: myDB
